name: medias_picker
description: A Flutter plugin for IOS and Android providing a simple way to get multiple pictures and videos.
version: 0.1.3+1
author: Lucas Britto <l_demello@hotmail.com>
homepage: https://github.com/lubritto/Flutter_Medias_Picker

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1

flutter:
  plugin:
    androidPackage: com.example.mediaspicker
    pluginClass: MediasPickerPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"
