name: medias_picker
description: A new Flutter plugin to get pictures and videos.
version: 0.1.3
author: Lucas Britto <l_demello@hotmail.com>
homepage: https://github.com/lubritto/Flutter_Medias_Picker

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.mediaspicker
    pluginClass: MediasPickerPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"
